# Generated by Django 4.0.5 on 2022-06-20 14:04

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raxit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_disc', models.CharField(max_length=500)),
                ('youtube_link', embed_video.fields.EmbedVideoField()),
                ('Product_status', models.CharField(choices=[('published', 'Published'), ('active', 'Active')], default='published', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
