# Generated by Django 4.0.5 on 2022-06-21 14:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('raxit', '0002_newproduct_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=50)),
                ('page_content', tinymce.models.HTMLField()),
                ('Product_status', models.CharField(choices=[('published', 'Published'), ('active', 'Active')], default='published', max_length=10)),
            ],
        ),
    ]
