# Generated by Django 4.0.5 on 2022-06-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raxit', '0003_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='Product_status',
            new_name='Page_status',
        ),
    ]
