# Generated by Django 4.0.5 on 2022-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raxit', '0004_rename_product_status_pages_page_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='contectusemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
